//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [Key]
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
    
        public virtual User User { get; set; }
    }
}
