//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ScheduleStop
    {
        [Key]
        public int ScheduleStopID { get; set; }
        public int ScheduleID { get; set; }
        public int StopID { get; set; }
        public System.DateTime ArrivalTime { get; set; }
    
        public virtual BusStop BusStop { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
