//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.BookedTickets = new HashSet<BookedTicket>();
        }
        [Key]
        public int TicketID { get; set; }
        public int RouteID { get; set; }
        public int BusID { get; set; }
        public decimal Fare { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedTicket> BookedTickets { get; set; }
        public virtual Bus Bus { get; set; }
        public virtual BusRoute BusRoute { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
